name: debug_di
description: "Debug feature DI layer - scope container, holder, and registrar."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  app_di:
  app_domain:
  app_presentation:
  core:
  debug_data:
  debug_di_interface:
  debug_domain:
  storage:
  flutter:
    sdk: flutter
  yx_scope: 1.0.2

dev_dependencies:
  build_runner: 2.5.4
