name: haptics
description: "A Flutter plugin for haptic feedback."
version: 1.0.0

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.surf.haptics
        pluginClass: HapticsPlugin
      ios:
        pluginClass: HapticsPlugin
      macos:
        pluginClass: HapticsPlugin
