name: storage
description: "Package with storage implementation."
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 9.2.4
  secure_enclave:
    path: ../secure_enclave
  shared_preferences: 2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
