name: storage
description: "Package with storage implementation."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: 3.11.0
  flutter: 3.41.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: 9.2.4
  secure_enclave:
    git: https://github.com/samirakhmedov/secure_enclave_plus.git
  shared_preferences: 2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
