name: splash_di
description: "Splash feature DI layer - scope container, holder, and registrar."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  splash_domain:
  splash_data:
  api:
  app_di:
  app_domain:
  app_presentation:
  database:
  network:
  yx_scope: 1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: 2.5.4
