name: app_basic
description: "App Template — GMS production build."
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  app_target:
  core:
  di_gms:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: false
  default-flavor: prod
