name: di_gms
description: "App DI GMS — Google Mobile Services dependency factories."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  analytics_gms:
  analytics_interface:
  flutter:
    sdk: flutter
  location_gms:
  location_interface:
  push_gms:
  push_interface:
