name: app_template

sdkPath: .fvm/flutter_sdk

categories:
  buildable:
    - packages/data/database
    - packages/data/api
    - packages/uikit
    - packages/features/**

ide:
  intellij:
    enabled: false

packages:
  - packages/**

scripts:
  format:
    run: dart format -l 120 .
    exec:
      concurrency: 6

  codegen:
    description: Run build_runner in all packages that use code generation
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 6
    packageFilters:
      dependsOn: build_runner


