name: location_gms
description: "Package with location implementation for GMS."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: 3.11.0

dependencies:
  device_info_plus: 11.5.0
  geolocator: 14.0.2
  location_interface: 
