// Information about the signature of the application
// https://developer.android.com/studio/publish/app-signing#secure-shared-keystore

android {
    signingConfigs {
        huawei {
            apply from: '../keystore/keystoreConfig.gradle'

            keyAlias huaweiKeystoreConfig.keyAlias
            keyPassword huaweiKeystoreConfig.keyPassword
            storeFile file(huaweiKeystoreConfig.storeFile)
            storePassword huaweiKeystoreConfig.storePassword
            enableV1Signing true
            enableV2Signing true
        }
    }
}
