name: haptics_presentation
description: "Haptics feature presentation layer - widgets and components."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  app_presentation:
  flutter:
    sdk: flutter
  haptics_domain:
  provider: 6.1.5

dev_dependencies:
  build_runner: 2.5.4
