name: api
description: "API package for the project"
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: 3.11.0
  flutter: 3.41.0

dependencies:
  dio: 5.8.0+1
  json_annotation: 4.9.0
  logger: 2.6.0 # for logging purpose
  retrofit: 4.6.0

dev_dependencies:
  build_runner: 2.5.4
  json_serializable: 6.9.5
  retrofit_generator: 9.6.0
