name: app_router
description: "App router — AppRouter and AppRoutes."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  flutter:
    sdk: flutter
  auto_route: 10.1.0+1
  splash_presentation:

