name: analytic
description: "Package with analytics implementation for HMS."
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  analytics_interface:
    path: ../interface
  huawei_analytics: ^6.12.0+301
