name: splash_presentation
description: "Splash feature presentation layer - widgets and screens."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.0
  flutter: 3.41.0

dependencies:
  app_assets:
  app_router:
  splash_domain:
  splash_di:
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  app_presentation:
  common_presentation:
  auto_route: 10.1.0+1
  provider: 6.1.5
  util:
  uikit:

dev_dependencies:
  auto_route_generator: 10.2.3
  build_runner: 2.5.4
