name: device_settings_presentation
description: "Device settings presentation layer - widgets and view models."
publish_to: none
version: 1.0.0
resolution: workspace

environment:
  sdk: 3.11.1
  flutter: 3.41.4

dependencies:
  app_di:
  app_presentation:
  device_settings_di:
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
